name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug Git
        run: |
          git status
          git log --oneline -n 5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Check NODE_ENV
        run: echo "NODE_ENV is set to $NODE_ENV"
        env:
          NODE_ENV: production

      - name: Build docs
        working-directory: ./apps/docs
        env:
          NODE_ENV: production
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/docs/dist
          user_name: 'b1z3rr4'
          user_email: 'b1z3rr4@gmail.com'
